{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/27275",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/27275/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/27275/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/27275/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/27275",
  "id": 426878983,
  "node_id": "MDU6SXNzdWU0MjY4Nzg5ODM=",
  "number": 27275,
  "title": "The training value of tf.keras.Model.call() becomes None when tf.keras.Model.fit(). (tf2.0.0-alpha0)",
  "user": {
    "login": "taxio",
    "id": 15796172,
    "node_id": "MDQ6VXNlcjE1Nzk2MTcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/15796172?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/taxio",
    "html_url": "https://github.com/taxio",
    "followers_url": "https://api.github.com/users/taxio/followers",
    "following_url": "https://api.github.com/users/taxio/following{/other_user}",
    "gists_url": "https://api.github.com/users/taxio/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/taxio/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/taxio/subscriptions",
    "organizations_url": "https://api.github.com/users/taxio/orgs",
    "repos_url": "https://api.github.com/users/taxio/repos",
    "events_url": "https://api.github.com/users/taxio/events{/privacy}",
    "received_events_url": "https://api.github.com/users/taxio/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1160540362,
      "node_id": "MDU6TGFiZWwxMTYwNTQwMzYy",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.0",
      "name": "TF 2.0",
      "color": "e79b38",
      "default": false,
      "description": "Issues relating to TensorFlow 2.0"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "omalleyt12",
      "id": 29100818,
      "node_id": "MDQ6VXNlcjI5MTAwODE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/omalleyt12",
      "html_url": "https://github.com/omalleyt12",
      "followers_url": "https://api.github.com/users/omalleyt12/followers",
      "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
      "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
      "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
      "repos_url": "https://api.github.com/users/omalleyt12/repos",
      "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
      "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2019-03-29T08:49:12Z",
  "updated_at": "2020-04-29T23:06:07Z",
  "closed_at": "2019-05-17T17:34:53Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I read the [document](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model#__call__) and implemented a model with `tf.keras.Model` as a subclass, but the value of training argument becomes `None`.\r\n\r\nIs this a bug? Or is my understanding wrong? This is a basic question, but please let me know.\r\n\r\nHere is the simplified code.\r\n\r\n```python\r\nimport numpy as np\r\nimport tensorflow as tf\r\nimport tensorflow.keras as tfk\r\n\r\n\r\nclass MyLayer(tfk.layers.Layer):\r\n    def __init__(self):\r\n        super(MyLayer, self).__init__()\r\n\r\n    def call(self, inputs, training=None):\r\n        # got: Tensor(\"keras_learning_phase:0\", shape=(), dtype=bool)\r\n        print(\"layer training arg: \", training)\r\n        \r\n        return inputs\r\n\r\n\r\nclass MyModel(tfk.Model):\r\n    def __init__(self):\r\n        super(MyModel, self).__init__()\r\n        self.l1 = MyLayer()\r\n\r\n    def call(self, inputs, training=None):\r\n        # want: Tensor(\"keras_learning_phase:0\", shape=(), dtype=bool)  got: None\r\n        print(\"model training arg: \", training)\r\n        \r\n        inputs = self.l1(inputs)\r\n        return inputs\r\n\r\n\r\nif __name__ == '__main__':\r\n    x = np.zeros((1, 2))\r\n    model = MyModel()\r\n    model.compile(loss=\"mse\", optimizer=\"sgd\")\r\n    model.fit(x, x, epochs=1)\r\n\r\n```\r\n\r\n\r\n\r\n**System information**\r\n\r\n- macOS Mojave 10.14.3\r\n- TensorFlow installed from : pip\r\n- TensorFlow version: 2.0.0a0\r\n- Python version: 3.5.6 (using pyenv)",
  "closed_by": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/27275/reactions",
    "total_count": 2,
    "+1": 2,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/27275/timeline",
  "performed_via_github_app": null
}
