{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43777",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43777/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43777/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43777/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/43777",
  "id": 714430888,
  "node_id": "MDU6SXNzdWU3MTQ0MzA4ODg=",
  "number": 43777,
  "title": "Trivial example does not save/restore weights, prints warnings from TensorFlow/Keras implementation",
  "user": {
    "login": "diyessi",
    "id": 8300383,
    "node_id": "MDQ6VXNlcjgzMDAzODM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8300383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/diyessi",
    "html_url": "https://github.com/diyessi",
    "followers_url": "https://api.github.com/users/diyessi/followers",
    "following_url": "https://api.github.com/users/diyessi/following{/other_user}",
    "gists_url": "https://api.github.com/users/diyessi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/diyessi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/diyessi/subscriptions",
    "organizations_url": "https://api.github.com/users/diyessi/orgs",
    "repos_url": "https://api.github.com/users/diyessi/repos",
    "events_url": "https://api.github.com/users/diyessi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/diyessi/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1946362326,
      "node_id": "MDU6TGFiZWwxOTQ2MzYyMzI2",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.3",
      "name": "TF 2.3",
      "color": "1d76db",
      "default": false,
      "description": "Issues related to TF 2.3"
    },
    {
      "id": 2046763290,
      "node_id": "MDU6TGFiZWwyMDQ2NzYzMjkw",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/Fixed%20in%20Nightly",
      "name": "Fixed in Nightly",
      "color": "5ecc37",
      "default": false,
      "description": "Issues that are resolved in nightly version"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "ravikyram",
    "id": 51902062,
    "node_id": "MDQ6VXNlcjUxOTAyMDYy",
    "avatar_url": "https://avatars.githubusercontent.com/u/51902062?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ravikyram",
    "html_url": "https://github.com/ravikyram",
    "followers_url": "https://api.github.com/users/ravikyram/followers",
    "following_url": "https://api.github.com/users/ravikyram/following{/other_user}",
    "gists_url": "https://api.github.com/users/ravikyram/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ravikyram/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ravikyram/subscriptions",
    "organizations_url": "https://api.github.com/users/ravikyram/orgs",
    "repos_url": "https://api.github.com/users/ravikyram/repos",
    "events_url": "https://api.github.com/users/ravikyram/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ravikyram/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "ravikyram",
      "id": 51902062,
      "node_id": "MDQ6VXNlcjUxOTAyMDYy",
      "avatar_url": "https://avatars.githubusercontent.com/u/51902062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ravikyram",
      "html_url": "https://github.com/ravikyram",
      "followers_url": "https://api.github.com/users/ravikyram/followers",
      "following_url": "https://api.github.com/users/ravikyram/following{/other_user}",
      "gists_url": "https://api.github.com/users/ravikyram/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ravikyram/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ravikyram/subscriptions",
      "organizations_url": "https://api.github.com/users/ravikyram/orgs",
      "repos_url": "https://api.github.com/users/ravikyram/repos",
      "events_url": "https://api.github.com/users/ravikyram/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ravikyram/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2020-10-05T00:02:15Z",
  "updated_at": "2020-10-05T15:53:43Z",
  "closed_at": "2020-10-05T15:53:41Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7, colab\r\n- TensorFlow installed from (source or binary): pip, colab\r\n- TensorFlow version (use command below): 2.3.1 (MacOS), v2.3.0-0-gb36436b087 2.3.0 (colab)\r\n- Python version: 3.8.5 (MacOS) 3.6.9 (colab)\r\n\r\n**Describe the current behavior**\r\nTrained weights are not restored, two warnings about the TensorFlow implementation are printed:\r\n`WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.\r\nInstructions for updating:\r\nThis property should not be used in TensorFlow 2.0, as updates are applied automatically.\r\nWARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\r\nInstructions for updating:\r\nThis property should not be used in TensorFlow 2.0, as updates are applied automatically.`\r\n\r\n**Describe the expected behavior**\r\nWeights are restored (test accuracy is consistent with saved model), no warnings printed.\r\nI find several *closed* bug reports from others over that look like the same problems  (lack of saving and the bogus warnings), going back to the 2.0.0 days. It has clearly not been fixed.\r\n\r\n**Standalone code to reproduce the issue**\r\n\r\n```python\r\nimport tensorflow as tf\r\n\r\n(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()\r\nx_train = x_train.astype('float32') / 255\r\nx_test = x_test.astype('float32') / 255\r\n\r\nmodel = tf.keras.models.Sequential([\r\n    tf.keras.layers.Flatten(),\r\n    tf.keras.layers.Dense(512, activation='relu'),\r\n    tf.keras.layers.Dense(10, activation='softmax')])\r\nmodel.compile(optimizer='rmsprop',\r\n              loss='sparse_categorical_crossentropy',\r\n              metrics=['accuracy'])\r\n\r\nmodel.fit(\r\n    x_train,\r\n    y_train,\r\n    epochs=8,\r\n    batch_size=128,\r\n    validation_split=0.2)\r\n\r\ntest_loss, test_acc = model.evaluate(x_test, y_test)\r\nprint('model_test_acc:', test_acc)\r\n\r\nmodel.save(\"my_saved_path\")\r\n\r\nsaved_model = tf.keras.models.load_model(\"my_saved_path\")\r\n\r\ntest_loss, test_acc = saved_model.evaluate(x_test, y_test)\r\nprint('saved_model_test_acc:', test_acc)\r\n```",
  "closed_by": {
    "login": "diyessi",
    "id": 8300383,
    "node_id": "MDQ6VXNlcjgzMDAzODM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8300383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/diyessi",
    "html_url": "https://github.com/diyessi",
    "followers_url": "https://api.github.com/users/diyessi/followers",
    "following_url": "https://api.github.com/users/diyessi/following{/other_user}",
    "gists_url": "https://api.github.com/users/diyessi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/diyessi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/diyessi/subscriptions",
    "organizations_url": "https://api.github.com/users/diyessi/orgs",
    "repos_url": "https://api.github.com/users/diyessi/repos",
    "events_url": "https://api.github.com/users/diyessi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/diyessi/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43777/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43777/timeline",
  "performed_via_github_app": null
}
