{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43518",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43518/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43518/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43518/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/43518",
  "id": 707817346,
  "node_id": "MDU6SXNzdWU3MDc4MTczNDY=",
  "number": 43518,
  "title": "Keras saved model gives different accuracy compared to the original model",
  "user": {
    "login": "peidaqi",
    "id": 18495787,
    "node_id": "MDQ6VXNlcjE4NDk1Nzg3",
    "avatar_url": "https://avatars.githubusercontent.com/u/18495787?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/peidaqi",
    "html_url": "https://github.com/peidaqi",
    "followers_url": "https://api.github.com/users/peidaqi/followers",
    "following_url": "https://api.github.com/users/peidaqi/following{/other_user}",
    "gists_url": "https://api.github.com/users/peidaqi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/peidaqi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/peidaqi/subscriptions",
    "organizations_url": "https://api.github.com/users/peidaqi/orgs",
    "repos_url": "https://api.github.com/users/peidaqi/repos",
    "events_url": "https://api.github.com/users/peidaqi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/peidaqi/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1946362326,
      "node_id": "MDU6TGFiZWwxOTQ2MzYyMzI2",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.3",
      "name": "TF 2.3",
      "color": "1d76db",
      "default": false,
      "description": "Issues related to TF 2.3"
    },
    {
      "id": 2046763290,
      "node_id": "MDU6TGFiZWwyMDQ2NzYzMjkw",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/Fixed%20in%20Nightly",
      "name": "Fixed in Nightly",
      "color": "5ecc37",
      "default": false,
      "description": "Issues that are resolved in nightly version"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "ravikyram",
    "id": 51902062,
    "node_id": "MDQ6VXNlcjUxOTAyMDYy",
    "avatar_url": "https://avatars.githubusercontent.com/u/51902062?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ravikyram",
    "html_url": "https://github.com/ravikyram",
    "followers_url": "https://api.github.com/users/ravikyram/followers",
    "following_url": "https://api.github.com/users/ravikyram/following{/other_user}",
    "gists_url": "https://api.github.com/users/ravikyram/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ravikyram/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ravikyram/subscriptions",
    "organizations_url": "https://api.github.com/users/ravikyram/orgs",
    "repos_url": "https://api.github.com/users/ravikyram/repos",
    "events_url": "https://api.github.com/users/ravikyram/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ravikyram/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "ravikyram",
      "id": 51902062,
      "node_id": "MDQ6VXNlcjUxOTAyMDYy",
      "avatar_url": "https://avatars.githubusercontent.com/u/51902062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ravikyram",
      "html_url": "https://github.com/ravikyram",
      "followers_url": "https://api.github.com/users/ravikyram/followers",
      "following_url": "https://api.github.com/users/ravikyram/following{/other_user}",
      "gists_url": "https://api.github.com/users/ravikyram/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ravikyram/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ravikyram/subscriptions",
      "organizations_url": "https://api.github.com/users/ravikyram/orgs",
      "repos_url": "https://api.github.com/users/ravikyram/repos",
      "events_url": "https://api.github.com/users/ravikyram/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ravikyram/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2020-09-24T03:11:57Z",
  "updated_at": "2020-09-24T16:48:17Z",
  "closed_at": "2020-09-24T15:08:36Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:\r\n- TensorFlow installed from (source or binary): binary\r\n- TensorFlow version (use command below): 2.3.0\r\n- Python version: 3.8.2\r\n- Bazel version (if compiling from source): N/A\r\n- GCC/Compiler version (if compiling from source): N/A\r\n- CUDA/cuDNN version: NVidia driver v450.66 CUDA 11.0\r\n- GPU model and memory: 2080ti 11GB\r\n\r\nYou can collect some of this information using our environment capture\r\n[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)\r\nYou can also obtain the TensorFlow version with:\r\n1. TF 1.0: `python -c \"import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)\"`\r\n2. TF 2.0: `python -c \"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)\"`\r\n\r\n\r\n**Describe the current behavior**\r\n**Describe the expected behavior**\r\n\r\nThe following code is supposed to output the same accuracy from model and loaded_model, but somehow they're different.\r\nIf I run model.predict instead, they're consistent though.\r\n\r\n```\r\nimport tensorflow as tf\r\nimport numpy as np\r\nfrom sklearn.model_selection import train_test_split\r\n\r\nx = np.random.rand(10000, 10)\r\ny = np.random.choice([0, 1], (10000, ))\r\n\r\nx_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)\r\n\r\n\r\nmodel = tf.keras.Sequential([\r\n    tf.keras.layers.Dense(128, activation='relu'),\r\n    tf.keras.layers.Dense(64, activation='relu'),\r\n    tf.keras.layers.Dense(32, activation='relu'),\r\n    tf.keras.layers.Dense(10, activation='softmax')\r\n])\r\n\r\nmodel.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics=['accuracy'])\r\n\r\nmodel.fit(x_train, y_train, epochs=10)\r\n\r\nmodel.save('./test_model/')\r\n\r\nloaded_model = tf.keras.models.load_model('./test_model/')\r\n\r\nprint(model.evaluate(x_test, y_test))\r\nprint(loaded_model.evaluate(x_test, y_test))\r\n```\r\n\r\n\r\n**Standalone code to reproduce the issue**\r\nProvide a reproducible test case that is the bare minimum necessary to generate\r\nthe problem. If possible, please share a link to Colab/Jupyter/any notebook.\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\ndiagnose the problem. If including tracebacks, please include the full\r\ntraceback. Large logs and files should be attached.\r\n",
  "closed_by": {
    "login": "peidaqi",
    "id": 18495787,
    "node_id": "MDQ6VXNlcjE4NDk1Nzg3",
    "avatar_url": "https://avatars.githubusercontent.com/u/18495787?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/peidaqi",
    "html_url": "https://github.com/peidaqi",
    "followers_url": "https://api.github.com/users/peidaqi/followers",
    "following_url": "https://api.github.com/users/peidaqi/following{/other_user}",
    "gists_url": "https://api.github.com/users/peidaqi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/peidaqi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/peidaqi/subscriptions",
    "organizations_url": "https://api.github.com/users/peidaqi/orgs",
    "repos_url": "https://api.github.com/users/peidaqi/repos",
    "events_url": "https://api.github.com/users/peidaqi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/peidaqi/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43518/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/43518/timeline",
  "performed_via_github_app": null
}
