{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38810",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38810/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38810/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38810/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/38810",
  "id": 605005604,
  "node_id": "MDU6SXNzdWU2MDUwMDU2MDQ=",
  "number": 38810,
  "title": "Verbose between epochs in tf version 2.2.0-rc3",
  "user": {
    "login": "Arvindia",
    "id": 17331990,
    "node_id": "MDQ6VXNlcjE3MzMxOTkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/17331990?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Arvindia",
    "html_url": "https://github.com/Arvindia",
    "followers_url": "https://api.github.com/users/Arvindia/followers",
    "following_url": "https://api.github.com/users/Arvindia/following{/other_user}",
    "gists_url": "https://api.github.com/users/Arvindia/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Arvindia/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Arvindia/subscriptions",
    "organizations_url": "https://api.github.com/users/Arvindia/orgs",
    "repos_url": "https://api.github.com/users/Arvindia/repos",
    "events_url": "https://api.github.com/users/Arvindia/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Arvindia/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1315098405,
      "node_id": "MDU6TGFiZWwxMzE1MDk4NDA1",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/regression%20issue",
      "name": "regression issue",
      "color": "50bcc4",
      "default": false,
      "description": "To spot regression issues in TF 2.0"
    },
    {
      "id": 1903591931,
      "node_id": "MDU6TGFiZWwxOTAzNTkxOTMx",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.2",
      "name": "TF 2.2",
      "color": "0052cc",
      "default": false,
      "description": "Issues related to TF 2.2"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "qiuminxu",
    "id": 3082188,
    "node_id": "MDQ6VXNlcjMwODIxODg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3082188?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/qiuminxu",
    "html_url": "https://github.com/qiuminxu",
    "followers_url": "https://api.github.com/users/qiuminxu/followers",
    "following_url": "https://api.github.com/users/qiuminxu/following{/other_user}",
    "gists_url": "https://api.github.com/users/qiuminxu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/qiuminxu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/qiuminxu/subscriptions",
    "organizations_url": "https://api.github.com/users/qiuminxu/orgs",
    "repos_url": "https://api.github.com/users/qiuminxu/repos",
    "events_url": "https://api.github.com/users/qiuminxu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/qiuminxu/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "qiuminxu",
      "id": 3082188,
      "node_id": "MDQ6VXNlcjMwODIxODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3082188?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/qiuminxu",
      "html_url": "https://github.com/qiuminxu",
      "followers_url": "https://api.github.com/users/qiuminxu/followers",
      "following_url": "https://api.github.com/users/qiuminxu/following{/other_user}",
      "gists_url": "https://api.github.com/users/qiuminxu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/qiuminxu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/qiuminxu/subscriptions",
      "organizations_url": "https://api.github.com/users/qiuminxu/orgs",
      "repos_url": "https://api.github.com/users/qiuminxu/repos",
      "events_url": "https://api.github.com/users/qiuminxu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/qiuminxu/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 20,
  "created_at": "2020-04-22T19:27:36Z",
  "updated_at": "2020-08-13T15:53:03Z",
  "closed_at": "2020-07-17T06:25:02Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Started to receive this today when **colab upgraded to 2.2.0-rc3.** Yesterday I've trained and tf.version was 2.2.0-rc2.\r\nThe model I'm using is created using tf.keras.\r\n\r\nEpoch 1/2\r\n2020-04-22 18:49:48.629597: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.\r\n1/2 [==============>...............] - ETA: 0s - loss: 0.8884 - categorical_accuracy: 0.7188 \r\n\r\n>2020-04-22 18:49:48.646518: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1479] CUPTI activity buffer flushed\r\n2020-04-22 18:49:48.646786: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:216]  GpuTracer has collected 133 callback api events and 133 activity events.\r\n2020-04-22 18:49:48.663147: I tensorflow/core/profiler/rpc/client/save_profile.cc:168] Creating directory: /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48\r\n2020-04-22 18:49:48.670211: I tensorflow/core/profiler/rpc/client/save_profile.cc:174] Dumped gzipped tool data for trace.json.gz to /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48/ea98f4633ef6.trace.json.gz\r\n2020-04-22 18:49:48.672098: I tensorflow/core/profiler/utils/event_span.cc:288] Generation of step-events took 0.026 ms\r\n2020-04-22 18:49:48.689016: I tensorflow/python/profiler/internal/profiler_wrapper.cc:87] Creating directory: /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48Dumped tool data for overview_page.pb to /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48/ea98f4633ef6.overview_page.pb\r\nDumped tool data for input_pipeline.pb to /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48/ea98f4633ef6.input_pipeline.pb\r\nDumped tool data for tensorflow_stats.pb to /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48/ea98f4633ef6.tensorflow_stats.pb\r\nDumped tool data for kernel_stats.pb to /content/drive/My Drive/Colab Notebooks/model_log_dirs_new1/logs_board/train/plugins/profile/2020_04_22_18_49_48/ea98f4633ef6.kernel_stats.pb\r\n\r\n2/2 [==============================] - 1s 306ms/step - loss: 0.9273 - categorical_accuracy: 0.6797 - val_loss: 0.7531 - val_categorical_accuracy: 0.7508\r\nEpoch 2/2\r\n2/2 [==============================] - 1s 253ms/step - loss: 0.8796 - categorical_accuracy: 0.7188 - val_loss: 0.6971 - val_categorical_accuracy: 0.7675\r\n\r\n**Between epochs I'm getting all this mumbo jumbo, previous version never resulted in this.**",
  "closed_by": {
    "login": "Arvindia",
    "id": 17331990,
    "node_id": "MDQ6VXNlcjE3MzMxOTkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/17331990?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Arvindia",
    "html_url": "https://github.com/Arvindia",
    "followers_url": "https://api.github.com/users/Arvindia/followers",
    "following_url": "https://api.github.com/users/Arvindia/following{/other_user}",
    "gists_url": "https://api.github.com/users/Arvindia/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Arvindia/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Arvindia/subscriptions",
    "organizations_url": "https://api.github.com/users/Arvindia/orgs",
    "repos_url": "https://api.github.com/users/Arvindia/repos",
    "events_url": "https://api.github.com/users/Arvindia/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Arvindia/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38810/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38810/timeline",
  "performed_via_github_app": null
}
